// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYTTCQeu2BdqKECCQWDDk9MdcRVcr9oYA',
    appId: '1:358472860686:web:ad1bfaf6190b5ce08c285f',
    messagingSenderId: '358472860686',
    projectId: 'hangman-english-game',
    authDomain: 'hangman-english-game.firebaseapp.com',
    storageBucket: 'hangman-english-game.firebasestorage.app',
    measurementId: 'G-F37NN0XF4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsAHK9g49iT7De8on8CYq-5StHrP283w',
    appId: '1:358472860686:android:fe04852350890c8c8c285f',
    messagingSenderId: '358472860686',
    projectId: 'hangman-english-game',
    storageBucket: 'hangman-english-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvClt07M19KpxG5El2X675VVpILbIZZ8o',
    appId: '1:358472860686:ios:3ee4afe063dbca4d8c285f',
    messagingSenderId: '358472860686',
    projectId: 'hangman-english-game',
    storageBucket: 'hangman-english-game.firebasestorage.app',
    iosBundleId: 'co.caospinap.hangmanEnglishLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvClt07M19KpxG5El2X675VVpILbIZZ8o',
    appId: '1:358472860686:ios:3ee4afe063dbca4d8c285f',
    messagingSenderId: '358472860686',
    projectId: 'hangman-english-game',
    storageBucket: 'hangman-english-game.firebasestorage.app',
    iosBundleId: 'co.caospinap.hangmanEnglishLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYTTCQeu2BdqKECCQWDDk9MdcRVcr9oYA',
    appId: '1:358472860686:web:a5036fc54e9fb6428c285f',
    messagingSenderId: '358472860686',
    projectId: 'hangman-english-game',
    authDomain: 'hangman-english-game.firebaseapp.com',
    storageBucket: 'hangman-english-game.firebasestorage.app',
    measurementId: 'G-R2EPVV25M8',
  );
}
